# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6739100be6b4c19d14801ece7ab9361a4dffc65383f7ac1846b30c9e3db795be7663cf43ac95644f57a3e424ddd90e477f00105188ba281ce4f2dca17c4f7d90

test:
  secret_key_base: 3ca6ea521c178a6106f65cc9646e0cd56b111c34a3b0c030ba176b15a628e1299dc42baac28404846b22d1ceb5b31cd503d88301a2f536842055315110c0674d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
